import { Brand, Product, Shipment, Campaign, Notification } from '../types';

export const MOCK_BRANDS: Brand[] = [
  {
    id: 'b1',
    name: 'Noire Studio',
    handle: '@noirestudio',
    logo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=120&h=120&fit=crop&crop=faces',
    coverImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&h=400&fit=crop',
    category: 'giyim',
    tags: ['minimal', 'kadın', 'günlük'],
    website: 'https://noirestudio.com',
    affiliateUrl: 'https://noirestudio.com?ref=butika',
    isVerified: true,
    isFavorite: true,
    productCount: 148,
    description: 'Minimalist kadın giyimde sanatsal bir anlayış.',
    rating: 4.8,
    lastActive: '2sa önce',
  },
  {
    id: 'b2',
    name: 'Arce Leather',
    handle: '@arceleather',
    logo: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=120&h=120&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&h=400&fit=crop',
    category: 'çanta',
    tags: ['deri', 'el yapımı', 'lüks'],
    website: 'https://arceleather.com',
    affiliateUrl: 'https://arceleather.com?ref=butika',
    isVerified: true,
    isFavorite: true,
    productCount: 64,
    description: 'El yapımı deri çantalar. Her parça benzersiz.',
    rating: 4.9,
    lastActive: '5sa önce',
  },
  {
    id: 'b3',
    name: 'Sol Kollektiv',
    handle: '@solkollektiv',
    logo: 'https://images.unsplash.com/photo-1511556820780-d912e42b4980?w=120&h=120&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=800&h=400&fit=crop',
    category: 'takı',
    tags: ['altın', 'gümüş', 'el yapımı', 'minimal'],
    website: 'https://solkollektiv.com',
    affiliateUrl: 'https://solkollektiv.com?ref=butika',
    isVerified: true,
    isFavorite: false,
    productCount: 92,
    description: 'Güneşin altınından ilham alan minimal takılar.',
    rating: 4.7,
    lastActive: '1g önce',
  },
  {
    id: 'b4',
    name: 'Velo Butikaue',
    handle: '@velobutikaue',
    logo: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=120&h=120&fit=crop&crop=faces',
    coverImage: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&h=400&fit=crop',
    category: 'giyim',
    tags: ['vintage', 'retro', 'kadın'],
    website: 'https://velobutikaue.com',
    affiliateUrl: 'https://velobutikaue.com?ref=butika',
    isVerified: false,
    isFavorite: true,
    productCount: 230,
    description: 'Vintage esintili modern kadın giyimi.',
    rating: 4.6,
    lastActive: '3g önce',
  },
  {
    id: 'b5',
    name: 'Kura Cosmetics',
    handle: '@kuracosmetics',
    logo: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=120&h=120&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&h=400&fit=crop',
    category: 'güzellik',
    tags: ['doğal', 'vegan', 'cilt bakımı'],
    website: 'https://kuracosmetics.com',
    affiliateUrl: 'https://kuracosmetics.com?ref=butika',
    isVerified: true,
    isFavorite: false,
    productCount: 55,
    description: 'Doğal ve vegan içeriklerle hazırlanan lüks kozmetik.',
    rating: 4.9,
    lastActive: '12sa önce',
  },
  {
    id: 'b6',
    name: 'Atmos Sneakers',
    handle: '@atmossneakers',
    logo: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=120&h=120&fit=crop&crop=center',
    coverImage: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=400&fit=crop',
    category: 'ayakkabı',
    tags: ['spor', 'streetwear', 'koleksiyon'],
    website: 'https://atmossneakers.com',
    affiliateUrl: 'https://atmossneakers.com?ref=butika',
    isVerified: true,
    isFavorite: false,
    productCount: 178,
    description: 'Sınırlı üretim sneaker koleksiyonları.',
    rating: 4.5,
    lastActive: '2g önce',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    brandId: 'b1',
    brandName: 'Noire Studio',
    brandLogo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=60&h=60&fit=crop&crop=faces',
    name: 'Asymmetric Linen Dress',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=500&fit=crop',
    price: 2450,
    originalPrice: 3200,
    currency: 'TL',
    url: 'https://noirestudio.com/dress-001',
    affiliateUrl: 'https://noirestudio.com/dress-001?ref=butika',
    category: 'elbise',
    tags: ['yaz', 'keten', 'asimetrik'],
    isSaved: true,
    isOnSale: true,
    savedAt: '2026-04-20',
    inStock: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Ekru', 'Siyah', 'Haki'],
    instagramPostId: 'ig_001',
  },
  {
    id: 'p2',
    brandId: 'b2',
    brandName: 'Arce Leather',
    brandLogo: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=60&h=60&fit=crop',
    name: 'Mini Saddle Bag',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=500&fit=crop',
    price: 4800,
    currency: 'TL',
    url: 'https://arceleather.com/mini-saddle',
    affiliateUrl: 'https://arceleather.com/mini-saddle?ref=butika',
    category: 'çanta',
    tags: ['deri', 'mini', 'saddle'],
    isSaved: true,
    isOnSale: false,
    savedAt: '2026-04-18',
    inStock: true,
    colors: ['Konyak', 'Siyah', 'Krem'],
    instagramPostId: 'ig_002',
  },
  {
    id: 'p3',
    brandId: 'b3',
    brandName: 'Sol Kollektiv',
    brandLogo: 'https://images.unsplash.com/photo-1511556820780-d912e42b4980?w=60&h=60&fit=crop',
    name: 'Gold Demi-Fine Ring Set',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=500&fit=crop',
    price: 980,
    originalPrice: 1200,
    currency: 'TL',
    url: 'https://solkollektiv.com/ring-set',
    affiliateUrl: 'https://solkollektiv.com/ring-set?ref=butika',
    category: 'takı',
    tags: ['altın', 'yüzük', 'set'],
    isSaved: true,
    isOnSale: true,
    savedAt: '2026-04-22',
    inStock: true,
    sizes: ['14', '15', '16', '17', '18'],
    instagramPostId: 'ig_003',
  },
  {
    id: 'p4',
    brandId: 'b4',
    brandName: 'Velo Butikaue',
    brandLogo: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=60&h=60&fit=crop&crop=faces',
    name: 'Velvet Blazer',
    image: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=400&h=500&fit=crop',
    price: 3100,
    currency: 'TL',
    url: 'https://velobutikaue.com/velvet-blazer',
    affiliateUrl: 'https://velobutikaue.com/velvet-blazer?ref=butika',
    category: 'ceket',
    tags: ['kadife', 'blazer', 'vintage'],
    isSaved: true,
    isOnSale: false,
    savedAt: '2026-04-15',
    inStock: false,
    sizes: ['XS', 'S', 'M'],
    colors: ['Bordo', 'Lacivert'],
    instagramPostId: 'ig_004',
  },
  {
    id: 'p5',
    brandId: 'b5',
    brandName: 'Kura Cosmetics',
    brandLogo: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=60&h=60&fit=crop',
    name: 'Luminous Glow Serum',
    image: 'https://images.unsplash.com/photo-1576426863848-c21f53c60b19?w=400&h=500&fit=crop',
    price: 650,
    currency: 'TL',
    url: 'https://kuracosmetics.com/glow-serum',
    affiliateUrl: 'https://kuracosmetics.com/glow-serum?ref=butika',
    category: 'serum',
    tags: ['vegan', 'aydınlatıcı', 'niacinamide'],
    isSaved: true,
    isOnSale: false,
    savedAt: '2026-04-21',
    inStock: true,
    instagramPostId: 'ig_005',
  },
  {
    id: 'p6',
    brandId: 'b1',
    brandName: 'Noire Studio',
    brandLogo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=60&h=60&fit=crop&crop=faces',
    name: 'Wide-Leg Trousers',
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400&h=500&fit=crop',
    price: 1890,
    currency: 'TL',
    url: 'https://noirestudio.com/trousers-wide',
    affiliateUrl: 'https://noirestudio.com/trousers-wide?ref=butika',
    category: 'pantolon',
    tags: ['geniş paça', 'yüksek bel', 'ofis'],
    isSaved: true,
    isOnSale: false,
    savedAt: '2026-04-19',
    inStock: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Krem', 'Siyah', 'Camel'],
    instagramPostId: 'ig_006',
  },
];

export const MOCK_SHIPMENTS: Shipment[] = [
  {
    id: 's1',
    brandId: 'b2',
    brandName: 'Arce Leather',
    brandLogo: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=60&h=60&fit=crop',
    orderNumber: 'ARC-2026-04891',
    trackingNumber: 'YK123456789TR',
    carrier: 'Yurtiçi Kargo',
    status: 'out_for_delivery',
    statusLabel: 'Dağıtımda',
    estimatedDelivery: 'Bugün, 18:00 - 21:00',
    lastUpdate: '10:42',
    lastLocation: 'İstanbul, Beşiktaş Şubesi',
    products: [
      {
        name: 'Mini Saddle Bag — Konyak',
        image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=100&h=100&fit=crop',
        quantity: 1,
      },
    ],
    totalAmount: 4800,
    currency: 'TL',
    createdAt: '2026-04-22T14:00:00Z',
    events: [
      {
        id: 'e1',
        timestamp: '24 Nis 10:42',
        location: 'İstanbul, Beşiktaş',
        description: 'Dağıtıma çıktı',
        status: 'out_for_delivery',
      },
      {
        id: 'e2',
        timestamp: '24 Nis 07:15',
        location: 'İstanbul Hub',
        description: 'Yerel dağıtım merkezine ulaştı',
        status: 'in_transit',
      },
      {
        id: 'e3',
        timestamp: '23 Nis 22:30',
        location: 'Ankara Hub',
        description: 'Transit merkezden çıktı',
        status: 'in_transit',
      },
      {
        id: 'e4',
        timestamp: '22 Nis 14:00',
        location: 'Arce Leather Depo',
        description: 'Kargoya verildi',
        status: 'shipped',
      },
    ],
  },
  {
    id: 's2',
    brandId: 'b1',
    brandName: 'Noire Studio',
    brandLogo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=60&h=60&fit=crop&crop=faces',
    orderNumber: 'NST-2026-01247',
    trackingNumber: 'MNG987654321',
    carrier: 'MNG Kargo',
    status: 'in_transit',
    statusLabel: 'Yolda',
    estimatedDelivery: 'Yarın, 25 Nisan',
    lastUpdate: 'Dün 19:30',
    lastLocation: 'Bursa Aktarma Merkezi',
    products: [
      {
        name: 'Asymmetric Linen Dress — Ekru',
        image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=100&h=100&fit=crop',
        quantity: 1,
      },
      {
        name: 'Wide-Leg Trousers — Siyah/S',
        image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=100&h=100&fit=crop',
        quantity: 1,
      },
    ],
    totalAmount: 4340,
    currency: 'TL',
    createdAt: '2026-04-22T11:00:00Z',
    events: [
      {
        id: 'e5',
        timestamp: '23 Nis 19:30',
        location: 'Bursa Aktarma',
        description: 'Aktarma merkezine ulaştı',
        status: 'in_transit',
      },
      {
        id: 'e6',
        timestamp: '22 Nis 11:00',
        location: 'Noire Studio Depo, İzmir',
        description: 'Kargoya verildi',
        status: 'shipped',
      },
    ],
  },
  {
    id: 's3',
    brandId: 'b5',
    brandName: 'Kura Cosmetics',
    brandLogo: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=60&h=60&fit=crop',
    orderNumber: 'KUR-2026-00552',
    trackingNumber: 'PTT445566778',
    carrier: 'PTT Kargo',
    status: 'delivered',
    statusLabel: 'Teslim Edildi',
    estimatedDelivery: '21 Nisan (Teslim Edildi)',
    lastUpdate: '21 Nis 14:15',
    lastLocation: 'İstanbul, Şişli — Komşunuza bırakıldı',
    products: [
      {
        name: 'Luminous Glow Serum',
        image: 'https://images.unsplash.com/photo-1576426863848-c21f53c60b19?w=100&h=100&fit=crop',
        quantity: 2,
      },
    ],
    totalAmount: 1300,
    currency: 'TL',
    createdAt: '2026-04-18T10:00:00Z',
    events: [
      {
        id: 'e7',
        timestamp: '21 Nis 14:15',
        location: 'İstanbul, Şişli',
        description: 'Teslim edildi — Komşuya bırakıldı',
        status: 'delivered',
      },
    ],
  },
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'c1',
    brandId: 'b1',
    brandName: 'Noire Studio',
    brandLogo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=60&h=60&fit=crop&crop=faces',
    title: 'Yaz Koleksiyonu %25 İndirim',
    description: 'Tüm yaz koleksiyonunda özel indirim! Kaçırma, stoklar sınırlı.',
    discount: 25,
    discountType: 'percent',
    endsAt: '2026-04-30T23:59:00',
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&h=300&fit=crop',
    code: 'BUTİKA25',
    url: 'https://noirestudio.com/yaz',
    affiliateUrl: 'https://noirestudio.com/yaz?ref=butika',
    isRead: false,
    isSponsored: false,
    createdAt: '2026-04-24T09:00:00',
  },
  {
    id: 'c2',
    brandId: 'b3',
    brandName: 'Sol Kollektiv',
    brandLogo: 'https://images.unsplash.com/photo-1511556820780-d912e42b4980?w=60&h=60&fit=crop',
    title: 'Yeni Koleksiyon: Cosmos',
    description: 'Evrenin güzelliğinden ilham alan yeni Cosmos koleksiyonu çıktı.',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&h=300&fit=crop',
    url: 'https://solkollektiv.com/cosmos',
    affiliateUrl: 'https://solkollektiv.com/cosmos?ref=butika',
    isRead: false,
    isSponsored: false,
    createdAt: '2026-04-23T14:00:00',
    endsAt: '2026-05-15T23:59:00',
  },
  {
    id: 'c3',
    brandId: 'b2',
    brandName: 'Arce Leather',
    brandLogo: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=60&h=60&fit=crop',
    title: 'Sınırlı Sayıda: Vintage Çanta',
    description: 'El yapımı vintage deri çantalardan yalnızca 20 adet üretildi.',
    discount: 500,
    discountType: 'fixed',
    endsAt: '2026-04-28T23:59:00',
    code: 'VINTAGE500',
    url: 'https://arceleather.com/vintage',
    affiliateUrl: 'https://arceleather.com/vintage?ref=butika',
    isRead: true,
    isSponsored: false,
    createdAt: '2026-04-22T10:00:00',
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: 'campaign',
    title: 'Noire Studio %25 indiriyor!',
    body: 'Kaydettiğin "Asymmetric Linen Dress" için özel kampanya başladı.',
    brandId: 'b1',
    brandName: 'Noire Studio',
    brandLogo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=60&h=60&fit=crop&crop=faces',
    isRead: false,
    createdAt: '2026-04-24T09:05:00',
  },
  {
    id: 'n2',
    type: 'shipment',
    title: 'Kargon yolda! 🚚',
    body: 'Arce Leather siparişin dağıtıma çıktı. Bugün 18:00-21:00 arası teslim edilecek.',
    brandId: 'b2',
    brandName: 'Arce Leather',
    brandLogo: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=60&h=60&fit=crop',
    isRead: false,
    createdAt: '2026-04-24T10:45:00',
  },
  {
    id: 'n3',
    type: 'newArrival',
    title: 'Sol Kollektiv: Yeni Koleksiyon',
    body: 'Takip ettiğin marka yeni koleksiyon yükledi. 18 yeni ürün seni bekliyor!',
    brandId: 'b3',
    brandName: 'Sol Kollektiv',
    brandLogo: 'https://images.unsplash.com/photo-1511556820780-d912e42b4980?w=60&h=60&fit=crop',
    isRead: true,
    createdAt: '2026-04-23T14:02:00',
  },
  {
    id: 'n4',
    type: 'priceDrop',
    title: 'Fiyat düştü! 🎉',
    body: '"Gold Demi-Fine Ring Set" %18 indirimde. Şimdi ₺980!',
    brandId: 'b3',
    brandName: 'Sol Kollektiv',
    brandLogo: 'https://images.unsplash.com/photo-1511556820780-d912e42b4980?w=60&h=60&fit=crop',
    isRead: true,
    createdAt: '2026-04-22T16:30:00',
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'Tümü', icon: '✦' },
  { id: 'giyim', label: 'Giyim', icon: '👗' },
  { id: 'çanta', label: 'Çanta', icon: '👜' },
  { id: 'takı', label: 'Takı', icon: '💍' },
  { id: 'ayakkabı', label: 'Ayakkabı', icon: '👠' },
  { id: 'güzellik', label: 'Güzellik', icon: '✨' },
  { id: 'aksesuar', label: 'Aksesuar', icon: '🕶️' },
  { id: 'ev', label: 'Ev', icon: '🏠' },
  { id: 'vintage', label: 'Vintage', icon: '🎞️' },
];
